### ISSUE TITLE
Not a directory \fable-generative-agents\static

### ISSUE THREAD

**Issue by philmaas** [fablestudio/fable-saga#20]
During setup i encountered this error when running server.py

Creating the folder called "static" manually in the repo dir fixes the issue.

`File "B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\aiohttp\web_urldispatcher.py", line 557, in __init__
    raise ValueError("Not a directory")
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "b:\fable-github\fable-generative-agents\fable_agents\server.py", line 297, in <module>
    app.router.add_static('/static', 'static')
  File "B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\aiohttp\web_urldispatcher.py", line 1124, in add_static
    resource = StaticResource(
               ^^^^^^^^^^^^^^^
  File "B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\aiohttp\web_urldispatcher.py", line 559, in __init__
    raise ValueError(f"No directory exists at '{directory}'") from error
ValueError: No directory exists at 'B:\fable-github\fable-generative-agents\static'`

**Comment by frankcarey** [comment]
shouldn't be an issue after refactor
