### ISSUE TITLE
Missing Prompt Templates (langchain) [Errno 2] No such file or directory: 'prompt_templates\\actions_v1.yaml

### ISSUE THREAD

**Issue by philmaas** [fablestudio/fable-saga#21]
Running the server.py complains about missing actions_v1.yaml files
The issue could be that I'm running the latest build 1.38.0-beta from itchio and not the unity project.

Edit: This seems to be a path issue in api.py (the files are in the repo) but the path was wrong 'prompt_templates\\actions_v1.yaml'`
Hardcoding the full path fixes the issue for now
`load_prompt("B:/fable-github/fable-generative-agents/fable_agents/prompt_templates/actions_v1.yaml")`

`======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
emit message-ack request-personas {"guids": []} to=H8r9X0uD4kREIIN0AAAB callback=<function SimulationAPI.reload_personas.<locals>.convert_to_personas at 0x000001DFF27D1A80>
emit message-ack request-affordances {"guids": []} to=H8r9X0uD4kREIIN0AAAB callback=<function SimulationAPI.reload_affordances.<locals>.convert_to_affordances at 0x000001DFF27D2520>
Task exception was never retrieved
future: <Task finished name='Task-37' coro=<AsyncServer._handle_event_internal() done, defined at B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\socketio\asyncio_server.py:513> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\socketio\asyncio_server.py", line 515, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\socketio\asyncio_server.py", line 549, in _trigger_event
    ret = await handler(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "b:\fable-github\fable-generative-agents\fable_agents\server.py", line 123, in message
    response = await API.gaia.create_reactions(resolution, persona_guid, last_action_by_persona, last_observations,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\fable-github\fable-generative-agents\fable_agents\api.py", line 286, in create_reactions
    prompt = load_prompt("prompt_templates/actions_v1.yaml")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\langchain\prompts\loading.py", line 125, in load_prompt
    return _load_prompt_from_file(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\langchain\prompts\loading.py", line 140, in _load_prompt_from_file
    with open(file_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'prompt_templates\\actions_v1.yaml'
emit message-ack request-locations {} to=H8r9X0uD4kREIIN0AAAB callback=<function SimulationAPI.reload_locations.<locals>.convert_to_locations at 0x000001DFF27D2520>
Task exception was never retrieved
future: <Task finished name='Task-599' coro=<AsyncServer._handle_event_internal() done, defined at B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\socketio\asyncio_server.py:513> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\socketio\asyncio_server.py", line 515, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\socketio\asyncio_server.py", line 549, in _trigger_event
    ret = await handler(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "b:\fable-github\fable-generative-agents\fable_agents\server.py", line 123, in message
    response = await API.gaia.create_reactions(resolution, persona_guid, last_action_by_persona, last_observations,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\fable-github\fable-generative-agents\fable_agents\api.py", line 286, in create_reactions
    prompt = load_prompt("prompt_templates/actions_v1.yaml")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\langchain\prompts\loading.py", line 125, in load_prompt
    return _load_prompt_from_file(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\fable-github\fable-generative-agents\.venv\Lib\site-packages\langchain\prompts\loading.py", line 140, in _load_prompt_from_file
    with open(file_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'prompt_templates\\actions_v1.yaml'`

**Comment by frankcarey** [comment]
shouldn't be an issue after refactor
